### ISSUE TITLE
Loading never finishes on macOS safari

### ISSUE THREAD

**Issue by gchilds** [mradionov/h264-bitstream-viewer#17]
Chrome works fine

**Comment by mradionov** [comment]
Hi, thank you for letting me know. I checked on Safari and it indeed throws an error after loading a file. I'll let you know when it's fixed.

**Comment by mradionov** [comment]
Fixed. Might need to hard reload the page to fetch a new version of the script.

**Comment by gchilds** [comment]
> Fixed. Might need to hard reload the page to fetch a new version of the script.

Thank you! It's working great!
