### ISSUE TITLE
Live demo does not load files

### ISSUE THREAD

**Issue by sandersdan** [mradionov/h264-bitstream-viewer#18]
Seems to be a bad `requestIdleCallback()` polyfill.

```
Uncaught (in promise) TypeError: Illegal invocation
    at FileReadStream.readNextChunk (FileReadStream.js:73)
```

![Screen Shot 2021-11-03 at 3 29 17 PM](https://user-images.githubusercontent.com/19863629/140207050-d0683b3e-6264-46e7-8b66-7bca7f17cea1.png)

**Comment by mradionov** [comment]
Hey, it's only supposed to work with .h264 files. Maybe I should make it more clear in the UI, and also handle errors when a wrong file type is uploaded. Here you can find a command which can help extract .h264 from .mp4 https://github.com/mradionov/h264-bitstream-viewer/blob/master/docs/h264.md#h264

**Comment by mradionov** [comment]
Buttery fingers, didn't mean to close

**Comment by sandersdan** [comment]
Title updated. Replacing the line with `window.requestIdleCallback(() => {` allows the app to function with raw H.264.

**Comment by mradionov** [comment]
I've fixed it. Thank you for letting me know!
